# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stad', models.CharField(default='(unknown)', max_length=50, verbose_name='Stad van dialect')),
                ('code', models.CharField(default='xxxxxx', max_length=6, verbose_name='Plaatscode (Kloeke)')),
                ('newcode', models.CharField(default='xxxxxx', max_length=6, verbose_name='Plaatscode (New Kloeke)')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting bij dialect')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='(unknown)', max_length=50, verbose_name='Dialectwoord')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting')),
                ('dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Dialect')),
            ],
        ),
        migrations.CreateModel(
            name='FieldChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('english_name', models.CharField(max_length=50)),
                ('dutch_name', models.CharField(max_length=50)),
                ('machine_value', models.IntegerField(help_text='The actual numeric value stored in the database. Created automatically.')),
            ],
            options={
                'ordering': ['field', 'machine_value'],
            },
        ),
        migrations.CreateModel(
            name='HelpChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200)),
                ('searchable', models.BooleanField(default=False)),
                ('display_name', models.CharField(max_length=50)),
                ('help_url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='(unknown)', max_length=50, verbose_name='Gloss voor dit lemma')),
                ('toelichting', models.TextField(blank=True, verbose_name='Omschrijving van het lemma')),
                ('bronnenlijst', models.TextField(blank=True, verbose_name='Bronnenlijst bij dit lemma')),
            ],
        ),
        migrations.CreateModel(
            name='Trefwoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='(unknown)', max_length=50, verbose_name='Trefwoord')),
                ('toelichting', models.TextField(blank=True, verbose_name='Toelichting bij trefwoord')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Lemma'),
        ),
        migrations.AddField(
            model_name='entry',
            name='trefwoord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Trefwoord'),
        ),
    ]
