# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-26 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dialect',
            old_name='newcode',
            new_name='nieuw',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='word',
            new_name='woord',
        ),
        migrations.RenameField(
            model_name='lemma',
            old_name='name',
            new_name='gloss',
        ),
        migrations.RenameField(
            model_name='trefwoord',
            old_name='name',
            new_name='woord',
        ),
    ]
